apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: speedtest
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: speedtest
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitor-iperf
  name: vp-iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vp-iperf-server
  template:
    metadata:
      labels:
        app: vp-iperf-server
    spec:
      containers:
      - image: vincent5753/zjst
        name: vp-iperf-server
        command: ["bash", "/speedtest/speedtest.sh"]
        env:
        - name: IsMaster
          value: "1"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: speedtest
      automountServiceAccountToken: true
---

apiVersion: v1
kind: Service
metadata:
  name: vp-iperf-svc
  namespace: default
  labels:
    app: vp-iperf-svc
spec:
  selector:
    app: vp-iperf-server
  ports:
    - name: iperf
      protocol: TCP
      port: 5201
      targetPort: 5201
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: speedmaster
  namespace: default
data:
  speedmaster: |
    node.pod

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtestresult
  namespace: default
data:
  results: |
    masternode.pod -> clientnode.pod -> 0

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: is-testing
  namespace: default
#  annotations:
#    kubectl.kubernetes.io/ttl: "1s"
data:
  is-testing: |
    0

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: monitor-iperf
  name: vp-iperf-client
spec:
  selector:
    matchLabels:
      app: vp-iperf-client
  template:
    metadata:
      labels:
        app: vp-iperf-client
    spec:
      initContainers:
      - name: chk-svc
        image: vincent5753/zjst
        command: ["bash", "-c", "for i in {1..100}; do sleep 1; if dig vp-iperf-svc.default.svc.cluster.local; then exit 0; fi; done; exit 1"]
      - name: speedtest
        image: vincent5753/zjst
        command: ["bash", "speedtest.sh"]
        env:
        - name: IsMaster
          value: "0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      containers:
      - image: vincent5753/ubuntu20.04
        name: normal-pod
        command: ["sleep", "infinity"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      serviceAccountName: speedtest
      automountServiceAccountToken: true
